repobase: "repo/"
maintainers:
  - name: Simon
    email: sife@adm.ku.dk
targets:
  - rpm
repo_url: "https://repo.ipi.dk/" # This is the base URL for the repositories. The url does not include the targets.