- name: the.repo # it must be the.repo to be recognized by the setup_instructions.j2 template (as the.repo.*.rpm).
  source: ./rpm_spec.j2
  type: template
  files_regex: ".*"
  arch: [noarch]
  destination: /etc/yum.repos.d/
  extra:
    url: "https://repo.ipi.dk/rpm/"
    summary: "simonfelding's extra utilities - $basearch"
    version: "1"


- name: "yq"
  source: mikefarah/yq
  files_regex: ^(?P<name>yq)_linux_(?P<arch>\w+)$
  type: github
  arch: [x86_64, aarch64]
  destination: /usr/bin/
  arch_translation:
    x86_64: amd64
    aarch64: arm64