- name: custom.repo
  source: ./rpm_spec.j2
  type: template
  files_regex: ".*"
  arch: [x86_64, aarch64]
  destination: /etc/yum.repos.d/
  extra:
    url: "https://rpm.ipi.dk"
    summary: "simonfelding's extra utilities - $basearch"
    version: "1"


- name: "yq"
  source: mikefarah/yq
  files_regex: ^(?P<name>yq)_linux_(?P<arch>\w+)$
  type: github
  arch: [x86_64, aarch64]
  destination: /usr/bin/
  arch_translation:
    x86_64: amd64
    aarch64: arm64