# Simple workflow for deploying static content to GitHub Pages
name: Deploy repo content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "*.yaml"
      - "**/*.py"
      - "**/*.j2"
      - ".github/workflows/deploy-repo.yml"
  schedule:
    - cron: "0 5 * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  IMAGE_NAME: ghcr.io/simonfelding/rpm/builder
  

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: repo/
          merge-multiple: true
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Run rpmbuilder
        run: "docker run --rm -v ${{ github.workspace }}:/build ${{ env.IMAGE_NAME }}"
      - uses: actions/upload-artifact@v4
        with:
          path: repo
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy page
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo/
          force_orphan: true
          cname: repo.ipi.dk
